# global settings
title: "PLATEAU Workshop"
description: "Bringing together Programming Languages and Human-Computer Interaction"
url: "https://schasins.com/plateau/" # the base hostname & protocol for your site, e.g. http://example.com
year: 2021
# colocated_url: "https://2020.splashcon.org/"
# colocated_logo: "./assets/images/splash2020.png"
# colocated_title: "SPLASH2020"
logo_height: "30px"
nth_plateau: "12th"
location: "@ Carnegie Mellon University, Pittsburgh PA USA"
workshop_date: "Tuesday November 9, 2021"
submission_date: "September 14, 2021"
# submission_site: "https://easychair.org/conferences/?conf=plateau2020"
# room_number_or_description: 
# registration_site: https://regmaster.com/2020conf/SPLASH20/register.php

organizers:
  - name: Sarah E. Chasins
    affiliation: University of California, Berkeley
  - name: Elena Glassman
    affiliation: Harvard University
  - name: Joshua Sunshine
    affiliation: Carnegie Mellon University

# panelists:


# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from

navbar_links:
  - title: "Home"
    url: "/"
    newtab: false
  - title: "Registration"
    url: "/registration"
    newtab: false
  - title: "Program"
    url: "/program"
    newtab: false
  - title: "Prior Year Sites"
    url: "/prior-year-sites"
    newtab: false
